EksamenWeb/Controllers/KøbstilbudController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EntityFrameworkModel;

namespace EksamenWeb.Controllers
{
    public class KøbstilbudController : Controller
    {
        private EksamenDatabaseEntities db = new EksamenDatabaseEntities();

        // GET: Købstilbud
        public ActionResult Index()
        {
            var købstilbud = db.Købstilbud.Include(k => k.Køber).Include(k => k.Salgsudbud);
            return View(købstilbud.ToList());
        }

        // GET: Købstilbud/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Købstilbud købstilbud = db.Købstilbud.Find(id);
            if (købstilbud == null)
            {
                return HttpNotFound();
            }
            return View(købstilbud);
        }

        // GET: Købstilbud/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Købstilbud/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KøbstilbudId,pris,køberId,salgsudbudId")] Købstilbud købstilbud)
        {
            if (ModelState.IsValid)
            {
                købstilbud.salgsudbudId = int.Parse(Session["salgsudbudId"].ToString());
                decimal højestePris = 0;
                foreach(Købstilbud k in db.Købstilbud)
                {
                    if(k.salgsudbudId == købstilbud.salgsudbudId)
                    {
                        if (k.pris > højestePris)
                        {
                            højestePris = k.pris;
                        }
                    }
                }
                if (købstilbud.pris > højestePris)
                {
                    var email = Session["email"].ToString();
                    var id = (from k in db.Køber where k.email == email select k.KøberId).FirstOrDefault();
                    købstilbud.køberId = id;
                    købstilbud.KøbstilbudId = db.Købstilbud.Count() + 1;
                    db.Købstilbud.Add(købstilbud);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Salgsudbuds");
                } else
                {
                    System.Diagnostics.Debug.WriteLine("Angivet pris skal være højere end: " + højestePris);
                }
            }
            return View(købstilbud);
        }

        // GET: Købstilbud/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Købstilbud købstilbud = db.Købstilbud.Find(id);
            if (købstilbud == null)
            {
                return HttpNotFound();
            }
            ViewBag.køberId = new SelectList(db.Køber, "KøberId", "navn", købstilbud.køberId);
            ViewBag.salgsudbudId = new SelectList(db.Salgsudbuds, "SalgsudbudId", "metaltype", købstilbud.salgsudbudId);
            return View(købstilbud);
        }

        // POST: Købstilbud/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KøbstilbudId,pris,køberId,salgsudbudId")] Købstilbud købstilbud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(købstilbud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.køberId = new SelectList(db.Køber, "KøberId", "navn", købstilbud.køberId);
            ViewBag.salgsudbudId = new SelectList(db.Salgsudbuds, "SalgsudbudId", "metaltype", købstilbud.salgsudbudId);
            return View(købstilbud);
        }

        // GET: Købstilbud/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Købstilbud købstilbud = db.Købstilbud.Find(id);
            if (købstilbud == null)
            {
                return HttpNotFound();
            }
            return View(købstilbud);
        }

        // POST: Købstilbud/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Købstilbud købstilbud = db.Købstilbud.Find(id);
            db.Købstilbud.Remove(købstilbud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EksamenWeb/Controllers/SalgsudbudsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EntityFrameworkModel;

namespace EksamenWeb.Controllers
{
    public class SalgsudbudsController : Controller
    {
        private EksamenDatabaseEntities db = new EksamenDatabaseEntities();

        // GET: Salgsudbuds
        public ActionResult Index()
        {
            return View(db.Salgsudbuds.ToList());
        }


        // GET: Salgsudbuds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salgsudbud salgsudbud = db.Salgsudbuds.Find(id);
            if (salgsudbud == null)
            {
                return HttpNotFound();
            }
            Session["salgsudbudId"] = id;
            return View(salgsudbud);
        }

        // GET: Salgsudbuds/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Salgsudbuds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SalgsudbudId,metaltype,mængde,tidsfrist")] Salgsudbud salgsudbud)
        {
            if (ModelState.IsValid)
            {
                db.Salgsudbuds.Add(salgsudbud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(salgsudbud);
        }

        // GET: Salgsudbuds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salgsudbud salgsudbud = db.Salgsudbuds.Find(id);
            if (salgsudbud == null)
            {
                return HttpNotFound();
            }
            return View(salgsudbud);
        }

        // POST: Salgsudbuds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SalgsudbudId,metaltype,mængde,tidsfrist")] Salgsudbud salgsudbud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salgsudbud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(salgsudbud);
        }

        // GET: Salgsudbuds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Salgsudbud salgsudbud = db.Salgsudbuds.Find(id);
            if (salgsudbud == null)
            {
                return HttpNotFound();
            }
            return View(salgsudbud);
        }

        // POST: Salgsudbuds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Salgsudbud salgsudbud = db.Salgsudbuds.Find(id);
            db.Salgsudbuds.Remove(salgsudbud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EksamenWeb/Views/Salgsudbuds/Create.cshtml
@model EntityFrameworkModel.Salgsudbud

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salgsudbud</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SalgsudbudId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalgsudbudId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalgsudbudId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.metaltype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.metaltype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.metaltype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mængde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mængde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mængde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tidsfrist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tidsfrist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tidsfrist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EksamenWeb/Views/Salgsudbuds/Delete.cshtml
@model EntityFrameworkModel.Salgsudbud

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salgsudbud</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.metaltype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.metaltype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mængde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mængde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tidsfrist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tidsfrist)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EksamenWeb/Views/Salgsudbuds/Details.cshtml
@model EntityFrameworkModel.Salgsudbud

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Salgsudbud</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.metaltype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.metaltype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mængde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mængde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tidsfrist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tidsfrist)
        </dd>

        <dt>
            Højeste bud: 
        </dt>

        <dd>
            @if (Model.Købstilbud.Count > 0)
            {
                @(Model.Købstilbud.Max(model => model.pris))
            } else
            {
                @("No bids yet...")
            }

        </dd>
        


    </dl>
</div>
<p>
    @Html.ActionLink("Return to list", "Index") | 
    @Html.ActionLink("Place bid", "Create", "Købstilbud")

</p>

EksamenWeb/Views/Salgsudbuds/Edit.cshtml
@model EntityFrameworkModel.Salgsudbud

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salgsudbud</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SalgsudbudId)

        <div class="form-group">
            @Html.LabelFor(model => model.metaltype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.metaltype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.metaltype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mængde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mængde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mængde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tidsfrist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tidsfrist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tidsfrist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EksamenWeb/Views/Salgsudbuds/Index.cshtml
@model IEnumerable<EntityFrameworkModel.Salgsudbud>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.metaltype)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mængde)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tidsfrist)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.tidsfrist.CompareTo(DateTime.Now) > 0)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.metaltype)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mængde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tidsfrist)
                </td>
                <td>
                    @Html.ActionLink("Place bid", "Details", new { id = item.SalgsudbudId})
                </td>
            </tr>
        }
    }

</table>